# Generated by Django 3.2.25 on 2024-05-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
